repos:
  - repo: local
    hooks:
      - id: fmt
        name: cargo fmt
        entry: cargo fmt --all -- --check
        language: system
        types: [rust]
        pass_filenames: false
      - id: clippy
        name: cargo clippy
        entry: cargo clippy --all -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
